#!/bin/sh
'''exec' C:/Users/moham/miniconda3/envs/heart_ml/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from nbclient.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
